apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: fcg-payments
  labels:
    app: payments
type: Opaque
stringData:
  PAYMENTS_DB_CONNECTION_STRING: $(PAYMENTS_DB_CONNECTION_STRING) 
  RABBITMQ_CONNECTION_STRING: $(RABBITMQ_CONNECTION_STRING)
  JWT_ISSUER: $(JWT_ISSUER)
  JWT_AUDIENCE: $(JWT_AUDIENCE)
  JWT_KEY: $(JWT_KEY)